#!/usr/bin/env python

import sys

def main(args):
    if len(args) != 2:
        print "Usage: ",args[0]," file"
        sys.exit(1)
    avg = calc(args[1])
    for v in avg:
        print "%lf" % (v) ,
    print ""

def calc(filename):
    fp = open(filename, "r")
    count = 0
    total = 0
    num   = -1
    average = []
    for line in fp:
        if len(line.strip()) == 0:
            continue
        if count != 0:
            total = total + float(line)
            count = count - 1
        elif line.startswith('#'):
            if num != -1:
                average.append(total / num)
                total = 0
            continue
        else:
            num = int(line)
            count = num
    if num != -1:
        average.append(total / num)
    fp.close()
    return average

if __name__ == "__main__":
    main(sys.argv)

